local m=dofile('files/usr/share/ddk-field-console/operator-v3.lua')
local c={validators=dofile('files/usr/share/ddk-field-console/operator-actions.lua'),interfaces={{name='lo'}},nmap_scans={{value='job-1-2',size=128,ino=7},{value='job-2-3',size=256,ino=8}},nmap_scans_newest={{value='job-2-3'}}}
local p=assert(m.prepare('network.compare_scans',{},c));assert(#p.source_scans==2 and p.source_scans[1].ino==7 and p.success_codes[2]==1)
assert(not m.prepare('network.compare_scans',{current='job-1-2'},c))
assert(not m.prepare('network.compare_scans',{baseline='../../etc/passwd'},c))
assert(not m.prepare('network.snmp',{community='fixture',oid='-Lo /tmp/file',profile='get'},c))
assert(not m.prepare('network.snmp',{community='fixture',oid='.1..2'},c))
assert(not m.prepare('network.snmp',{version='3',username='fixture',level='authPriv',authpass='12345678'},c))
p=assert(m.prepare('network.snmp',{version='3',username='fixture',level='authPriv',authpass='12345678',privpass='87654321'},c))
assert(#p.private_inputs==2 and p.options.authpass=='[REDACTED]' and not p.argv_preview:find('12345678',1,true))
assert(p.required_executables[2]=='/usr/libexec/ddk-snmp/snmpget')
assert(p.options.privacy=='AES' and p.argv_preview:find('AES',1,true))
for _,privacy in ipairs({'AES','AES-192','AES-256','AES-192-C','AES-256-C','DES'}) do
 p=assert(m.prepare('network.snmp',{version='3',username='fixture',level='authPriv',authpass='12345678',privpass='87654321',privacy=privacy,profile='walk'},c))
 assert(p.options.privacy==privacy and p.required_executables[2]=='/usr/libexec/ddk-snmp/snmpwalk')
end
assert(not m.prepare('network.snmp',{version='3',privacy='AES;id'},c))
p=assert(m.prepare('network.smb',{operation='transfer',share='Field Files',path='Folder;with spaces',guest=false,username='fixture',password='test-only-password'},c))
assert(p.confirmation.required and p.msp_workspace=='smb' and p.workspaces[1].reserve_size==3145728)
assert(p.options.password=='[REDACTED]' and not p.argv_preview:find('test-only-password',1,true))
assert(not m.prepare('network.smb',{operation='directory',share='host/share'},c))
assert(not m.prepare('network.smb',{guest=false,username='user%password'},c))
assert(not m.prepare('network.tracepath',{host='-f/etc/passwd'},c))
assert(not m.prepare('network.tracepath',{family='ipv6',length=28},c))
assert(m.prepare('network.tracepath',{host='2001:db8::4',family='ipv6'},c))
print('DDK_NETWORK_TOOLS_OK: case selection, credentials, v3 compatibility, target and transfer validation')
